// Generated by CoffeeScript 1.6.3
exports.create = function(model, dom) {
  var self;
  self = this;
  return dom.addListener(document, "keydown", function(e) {
    if (model.get('keydown') && model.get('show')) {
      if (e.keyCode === 27) {
        return self.close("escape");
      }
    }
  });
};

exports.show = function() {
  return this.model.set("show", true);
};

exports.close = function(action) {
  return this.model.pass({
    action: action
  }).set("show", false);
};

exports._click = function(e) {
  var action;
  action = e.target.getAttribute("data-action");
  if (action) {
    return this.close(action);
  }
};
